baseurl: "https://m4jing.github.io/"
# languageCode: "en-us"
languageCode: "zh-cn"
title: "Jing Ma | 马景"
theme: hugo-lithium
enableEmoji: true
hasCJKLanguage: true
footnotereturnlinkcontents: "↩"

googleAnalytics: 'G-KF5S5V8P5Z'
# disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year-:month-:day/:slug/
  # inspire: /:year-:month/:slug/

menu:
  main:
    # - name: Research
    #   url: /research/
    #   weight: 1
    - name: English-in-use
      url: https://m4jing.github.io/english-in-use
      params:
        # rel: external
        # class: center
        target: _blank
      # pre: <i class="fa fa-heart">i</i>
      title: Use your English
      weight: 1
    - name: Post
      pageRef: /post/
      # url: /post/
      title: Ideas and thoughts
      weight: 1
    - name: Inspire
      url: /inspire/
      title: Thinking and practice
      weight: 2
    - name: About
      url: /about/
      title: Know more about Jing Ma
      weight: 3
    # - name: Running
    #   url: /running/
    #   weight: 2
    # - name: Project
    #   url: /project/
    #   weight: 3

params:
  author: Jing Ma(@m4jing)
  description: Jing Ma's Web Space. A certified running coach, love Data Science, (R/ggplot2/tidyverse/Python), Running. 马景的个人网站。喜欢数据科学的跑步教练：R语言、ggplot2、tidyverse、Python，也喜欢跑步：马景教练，跑向巅峰。
  footer: "&copy; Jing Ma 2014 - {Year}"
  # footer: "&copy;[Jing Ma](/) 2014 - {Year}"
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    # - yaml
  # highlightjsTheme: Gml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  customCSS:
    - css/custom.css
  favicon: c4c33ca8ea0842fda881a6fc16abf162.png
  # favicon: favicon.png
  # favicon: favicon.ico
  logo:
    alt: Logo
    height: 50
    url: c4c33ca8ea0842fda881a6fc16abf162.png
    # url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  highlight:
    codeFences: true
    style: "github"
    linenos: true
  goldmark:
    renderer:
      unsafe: yes
